name: Snyk Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Snyk
        run: npm install -g snyk
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Build Docker image
        run: docker build -t my-app:latest .
      - name: Test Docker image for vulnerabilities
        run: snyk container test my-app:latest
